[tool.poetry]
name = "splitwise"
version = "0.1.0"
description = ""
authors = ["Zhijun <zliao@nuna.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipdb = "0.13.13"
pytest = "7.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
