# Generated by Django 5.0.2 on 2024-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='balance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
