# Generated by Django 5.0.2 on 2024-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_group_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='balance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
